### ISSUE TITLE
If is initial commit, pretty-quick throw e error.

### ISSUE THREAD

**Issue by BiosSun** [azz/pretty-quick#11]
## env

* pretty-quick: `1.2.2`
* husky: `0.14.3`
* node: `8.9.3`
* yarn: `1.3.2`
* System: `macOS 10.13.2`

## description

If is initial commit, pretty-quick throw e error:

``` bash
husky > npm run -s precommit (node v8.9.3)

~/demo/node_modules/execa/index.js:303
		throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
		^

Error: fatal: Needed a single revision

    at Function.module.exports.sync (~/demo/node_modules/execa/index.js:303:26)
    at runGit (~/demo/node_modules/pretty-quick/dist/scms/git.js:29:53)
    at Object.exports.getSinceRevision (~/demo/node_modules/pretty-quick/dist/scms/git.js:37:10)
    at exports.default (~/demo/node_modules/pretty-quick/dist/index.js:39:33)
    at Object.<anonymous> (~/demo/node_modules/pretty-quick/bin/pretty-quick.js:12:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by azz** [comment]
Fixed in https://github.com/azz/pretty-quick/releases/tag/v1.2.3
