### ISSUE TITLE
SyntaxError: ';' expected in package.json

### ISSUE THREAD

**Issue by BuZZ-dEE** [azz/pretty-quick#23]
I'm trying to commit the following:

```diff
⋊> ~/W/web-app on prettier ⨯   git diff --staged                                                                                                                              14:20:30
diff --git a/package.json b/package.json
index b7801607..703581e1 100644
--- a/package.json
+++ b/package.json
@@ -15,7 +15,7 @@
     "buildwatcher": "ng build --watch",
     "pree2e": "webdriver-manager update",
     "e2e": "ng e2e",
-    "precommit": "pretty-quick --staged"
+    "precommit": "pretty-quick --staged",
     "tslint-check": "tslint-config-prettier-check ./tslint.json"
   },
   "private": true,
```

but I get the following error:

```
⋊> ~/W/web-app on prettier ⨯   git commit -m "Add missing comma"                                                                                                              14:16:32
husky > npm run -s precommit (node v6.10.2)

🔍  Finding changed files since git revision 9cb1833d.
🎯  Found 1 changed file.
/home/user/Workspace/web-app/node_modules/prettier/index.js:24285
      throw error;
      ^

SyntaxError: ';' expected. (2:9)
  1 | {
> 2 |   "name": "web-app",
    |         ^
  3 |   "version": "0.0.0",
  4 |   "license": "MIT",
  5 |   "angular-cli": {},
    at createError (/home/user/Workspace/web-app/node_modules/prettier/parser-typescript.js:1:194)
    at Object.parse (/home/user/Workspace/web-app/node_modules/prettier/parser-typescript.js:1:18102)
    at Object.parse$4 [as parse] (/home/user/Workspace/web-app/node_modules/prettier/index.js:24274:19)
    at formatWithCursor (/home/user/Workspace/web-app/node_modules/prettier/index.js:33650:27)
    at format (/home/user/Workspace/web-app/node_modules/prettier/index.js:33695:10)
    at format (/home/user/Workspace/web-app/node_modules/prettier/index.js:33945:12)
    at exports.default (/home/user/Workspace/web-app/node_modules/pretty-quick/dist/formatFiles.js:18:41)
    at exports.default (/home/user/Workspace/web-app/node_modules/pretty-quick/dist/index.js:48:29)
    at Object.<anonymous> (/home/user/Workspace/web-app/node_modules/pretty-quick/bin/pretty-quick.js:12:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by azz** [comment]
Looks like it thinks it is TypeScript for some reason? Which version of Prettier are you using?

**Comment by ercarignan** [comment]
I'm running into this same issue - trying to follow the instructions here: https://medium.com/@victormejia/setting-up-prettier-in-an-angular-cli-project-2f50c3b9a537.  
I have version 1.11.1 of Prettier, and 1.4.1 of pretty-quick.

**Comment by MrEmelianenko** [comment]
Yeah, guys. I got the same error.

**Comment by azz** [comment]
If anyone can put together a concrete set of reproduction steps, or repository, that would go a long way towards getting this fixed.

**Comment by BuZZ-dEE** [comment]
I'm using:
`"prettier": "1.10.2",`

**Comment by BuZZ-dEE** [comment]
I now created a new Typescript project and I had the same problem. I also saw that in the [`.prettierignore`](https://github.com/prettier/prettier-vscode/blob/master/.prettierignore) file from the [prettier-vscode](https://github.com/prettier/prettier-vscode/) repository the `package.json` is ignored.

**Comment by azz** [comment]
(Sorry for the long delay) 

@BuZZ-dEE Found the issue with your setup, I suspect this is what is happening to everyone. 

Your `.prettierrc` file has `parser: typescript`. This is picked up by `pretty-quick` and overrides the extension-based parser inference. Fix is to remove the `parser` setting and let Prettier figure it out from the extension.

**Comment by azz** [comment]
Because it's not a bug. The config file is effectively saying "For all files, use the typescript parser". There's nothing that can really be done in `pretty-quick`.
