### ISSUE TITLE
Error when commiting

### ISSUE THREAD

**Issue by DavideCarvalho** [azz/pretty-quick#61]
I was using pretty-quick and it was working fine, but since yesterday i'm getting this error:
```
C:\Users\davi.carvalho\Documents\afe-pipeline\node_modules\pretty-quick\dist\scms\git.js:43
    throw error;
    ^

Error
    at Function.module.exports.sync (C:\Users\davi.carvalho\Documents\afe-pipeline\node_modules\pretty-quick\node_modules\execa\index.js:303:26)
    at runGit (C:\Users\davi.carvalho\Documents\afe-pipeline\node_modules\pretty-quick\dist\scms\git.js:29:53)
    at Object.exports.getSinceRevision (C:\Users\davi.carvalho\Documents\afe-pipeline\node_modules\pretty-quick\dist\scms\git.js:38:12)
    at exports.default (C:\Users\davi.carvalho\Documents\afe-pipeline\node_modules\pretty-quick\dist\index.js:44:33)
    at Object.<anonymous> (C:\Users\davi.carvalho\Documents\afe-pipeline\node_modules\pretty-quick\bin\pretty-quick.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
husky > pre-commit hook failed (add --no-verify to bypass)
```
I tried reinstalling the dependencies but it didn't work

**Comment by jantimon** [comment]
Did it also show an error message?

**Comment by DavideCarvalho** [comment]
Nope, only this

**Comment by DavideCarvalho** [comment]
Since i’m working inside a client, it’s possible that it’s a network problem, I’ll take a look

**Comment by jantimon** [comment]
The error happens here:

https://unpkg.com/pretty-quick@1.10.0/dist/scms/git.js

```
const getSinceRevision = exports.getSinceRevision = (directory, { staged, branch }) => {
  try {
    const revision = staged ? 'HEAD' : runGit(directory, ['merge-base', 'HEAD', branch || 'master']).stdout.trim();
    return runGit(directory, ['rev-parse', '--short', revision]).stdout.trim();
  } catch (error) {
    if (/HEAD/.test(error.message) || staged && /Needed a single revision/.test(error.message)) {
      return null;
    }
    throw error;
  }
};
````

But this is quite unrelated to the last changes we did.

**Comment by jantimon** [comment]
Cool 👍- can we close this issue then?

**Comment by azz** [comment]
Let's close it. Sounds like git itself exited nonzero with no output. If it props up again we can investigate further.
